name: strudl
description: Visualize your studying efforts (hell). Like in GitHub.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  intl: ^0.17.0
  get_storage: ^2.0.3
  path_provider: ^2.0.11
  flutter_colorpicker: ^1.0.3
  date_time_picker: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.8.2
  multi_select_flutter: ^4.1.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.2.1

flutter:
  uses-material-design: true
